"""Added favourite movies association table and relationship

Revision ID: 367d1a9a0cb1
Revises: ce8fdc32dc78
Create Date: 2026-05-13 22:13:18.149065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367d1a9a0cb1'
down_revision = 'ce8fdc32dc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_movies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_movies')
    # ### end Alembic commands ###
